import { createQuorumClient, TOKENS, unitsToCents } from '@quorum/paymaster'
import { privateKeyToAccount } from 'viem/accounts'

/**
 * Funds the treasury from the Moderato faucet.
 *
 * Deliberately not the `tempo wallet fund` flow from Tempo's CLI skill doc. That one
 * targets mainnet (chain 4217) and moves real money through a logged-in wallet, which
 * is the wrong tool for the job here twice over: this project settles on Moderato, and
 * the treasury key is a throwaway generated by `npm run setup`. Funding a mainnet
 * wallet would spend real funds and still leave the testnet treasury empty.
 *
 * The faucet is an ordinary Tempo action, so this needs no CLI, no login and no
 * account: the same client that pays wages asks for the funds to pay them with.
 */

function requireEnv(name) {
  const value = process.env[name]
  if (!value || value === '0x')
    throw new Error(`${name} is not set. Run \`npm run setup\` first, then retry.`)
  return value
}

async function main() {
  const network = process.env.QUORUM_NETWORK === 'mainnet' ? 'mainnet' : 'testnet'

  // The faucet only exists on testnet, and asking for free money on mainnet is not a
  // thing that quietly does nothing — it is a thing that fails confusingly.
  if (network !== 'testnet') {
    console.error('Refusing to run: QUORUM_NETWORK is not testnet.')
    console.error('There is no faucet on mainnet — fund the treasury there yourself.')
    process.exit(1)
  }

  const privateKey = requireEnv('QUORUM_TREASURY_KEY')
  const account = privateKeyToAccount(privateKey)
  const client = createQuorumClient({
    network,
    privateKey,
    ...(process.env.QUORUM_RPC_URL ? { rpcUrl: process.env.QUORUM_RPC_URL } : {}),
  })

  console.log('')
  console.log('  Funding the treasury from the Moderato faucet')
  console.log('  ' + '─'.repeat(58))
  console.log(`  Address:  ${account.address}`)
  console.log(`  Network:  Tempo Testnet (Moderato), chain 42431`)
  console.log('')

  const before = await balances(client, account.address)
  console.log(`  Before:   pathUSD ${before.pathUsd}c`)

  process.stdout.write('  Asking the faucet… ')
  const receipts = await client.faucet.fundSync({ account: account.address, timeout: 60_000 })
  console.log(`done, ${receipts.length} transaction(s)`)

  const after = await balances(client, account.address)
  console.log(`  After:    pathUSD ${after.pathUsd}c`)
  console.log('')

  for (const receipt of receipts)
    console.log(`  https://explore.testnet.tempo.xyz/tx/${receipt.transactionHash}`)
  console.log('')

  if (after.pathUsd <= before.pathUsd) {
    console.log('  The balance did not increase. The faucet may be rate-limiting this')
    console.log('  address, or the transactions may not have carried pathUSD. Check the')
    console.log('  links above before assuming wages will settle.')
    process.exit(1)
  }

  const wages = Math.floor(after.pathUsd / 2)
  console.log(`  That is roughly ${wages} wages at 2c each.`)
  console.log('')
  console.log('  Now prove settlement end to end:')
  console.log('    npm run gateway     # in another terminal')
  console.log('    npm run settle      # sends one real wage and prints the explorer link')
  console.log('')
}

async function balances(client, address) {
  const pathUsd = await client.token
    .getBalance({ token: TOKENS.pathUsd, account: address })
    .then((b) => unitsToCents(b.amount))
    .catch(() => 0)
  return { pathUsd }
}

main().catch((error) => {
  console.error('')
  console.error(`  Failed: ${error instanceof Error ? error.message : error}`)
  console.error('')
  process.exit(1)
})
