import { randomBytes } from 'node:crypto'
import { networkInterfaces } from 'node:os'
import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { createInterface } from 'node:readline/promises'
import { privateKeyToAccount } from 'viem/accounts'

/**
 * First-run setup.
 *
 * Writes a working `.env` so the gateway starts on the first attempt. Everything it
 * generates is a fresh testnet key with no funds, which is deliberate: the point is to
 * get the thing running and inspectable, not to hand anybody a funded account.
 *
 * The gateway refuses to boot without these four values, so the alternative to this
 * script is reading an error message, generating a key by hand, and looking up what
 * `MPP_SECRET_KEY` needs to be. That is three chances to give up before seeing
 * anything work.
 */

const ENV_PATH = '.env'

async function main() {
  const force = process.argv.includes('--force')

  if (existsSync(ENV_PATH) && !force) {
    const current = await readFile(ENV_PATH, 'utf8')
    const missing = ['QUORUM_TREASURY_KEY', 'QUORUM_RECIPIENT', 'MPP_SECRET_KEY'].filter((key) => {
      const match = current.match(new RegExp(`^${key}=(.*)$`, 'm'))
      return !match || match[1].trim() === '' || match[1].trim() === '0x'
    })
    if (missing.length === 0) {
      console.log('.env already looks complete. Nothing to do.')
      console.log('Run with --force to replace it with fresh keys.')
      return
    }
    console.log(`.env exists but is missing: ${missing.join(', ')}`)
    const rl = createInterface({ input: process.stdin, output: process.stdout })
    const answer = await rl.question('Replace it with a freshly generated one? [y/N] ')
    rl.close()
    if (answer.trim().toLowerCase() !== 'y') {
      console.log('Left alone. Fill those values in by hand, or rerun with --force.')
      return
    }
  }

  // A throwaway testnet key. It holds nothing until you fund it from the faucet.
  const treasuryKey = `0x${randomBytes(32).toString('hex')}`
  const treasury = privateKeyToAccount(treasuryKey)
  const paymentSecret = randomBytes(32).toString('base64')

  // A phone on the same network reaches the app at a LAN address, which is a different
  // origin again, so it has to be allowed up front or every worker request is blocked
  // by the browser with nothing in the gateway log to explain why.
  const lan = Object.values(networkInterfaces())
    .flat()
    .filter((iface) => iface && iface.family === 'IPv4' && !iface.internal)
    .map((iface) => `http://${iface.address}:5173`)
  const workerOrigins = ['http://localhost:5173', 'http://localhost:5199', ...lan]

  const env = `# Generated by \`npm run setup\` on ${new Date().toISOString().slice(0, 10)}.
# These are fresh testnet keys holding nothing. Fund the treasury from the Moderato
# faucet before expecting wages or refunds to land:
#   https://tempo.xyz/developers/docs/guide/getting-funds

QUORUM_NETWORK=testnet

# Pays wages and refunds. Server-side only — never put a funded mainnet key here.
QUORUM_TREASURY_KEY=${treasuryKey}

# Where callers send payment. Set to the treasury's own address so a demo settles
# against one account; in production these should be separate.
QUORUM_RECIPIENT=${treasury.address}

# Binds payment challenges to their contents.
MPP_SECRET_KEY=${paymentSecret}

PORT=8787
QUORUM_PUBLIC_URL=http://localhost:8787
QUORUM_STATE_PATH=data/workers.json
QUORUM_WAGE_CENTS=2
QUORUM_WORKER_APP_ORIGINS=${workerOrigins.join(',')}

# Mounts /v1/dev/question and /v1/dev/worker-history so the worker app can be
# exercised without a funded treasury. Testnet only, and refused on mainnet even if
# set to true. Turn this off before showing anyone a real deployment.
QUORUM_DEV_ENDPOINTS=true
`

  await writeFile(ENV_PATH, env)

  console.log('')
  console.log('  Wrote .env')
  console.log('  ' + '─'.repeat(58))
  console.log(`  Treasury address:  ${treasury.address}`)
  console.log('  Network:           Moderato testnet (chain 42431)')
  console.log('  Dev routes:        on, so you can see the app work with no funds')
  console.log('')
  console.log('  Next:')
  console.log('    npm run build')
  console.log('    npm run gateway     # terminal 1, on :8787')
  console.log('    npm run worker      # terminal 2, on :5173')
  console.log('')
  console.log('  Then open http://localhost:5173')
  if (lan.length > 0) console.log(`  Or from a phone on the same network: ${lan[0]}`)
  console.log('')
  console.log('  The treasury holds nothing, so wages will fail and say so in the')
  console.log('  gateway log. Everything else works. To settle for real, fund it:')
  console.log('    https://tempo.xyz/developers/docs/guide/getting-funds')
  console.log('')
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
